apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
     containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
          #hostPort: 27017
          name: mongo
        #volumeMounts:
        #- mountPath: /directorio-dentro-de-contenedor
        #  name: directory0
      #volumes:
      #- hostPath:
      #    path: /maquina-huesped
      #    type: Directory
      #  name: directory0
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    app: mongo
---
