---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - env:
        - name: HOST
          value: 'mongo'
        image: minodejs:v1.0
        name: nodejs
        ports:
        - containerPort: 3000
          #hostPort: 3000
          name: nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - name: nodejs
    port: 3000
    targetPort: 3000
  selector:
    app: backend
---
